### ISSUE TITLE
Masterticket: Copy content from ploneconf_acsrcontent mosaic Frontpage and navigation related subfolders into main site

### ISSUE THREAD

**Issue by acsr** [jazkarta/ploneconf2016.policy#2]
The following tasks can be distributed into subtickets as needed:
## Pressing ToDos:
- [x] Copy the front page and folders of the Plone site "ploneconf_acsrcontent" as unpublished into the live site, without affecting current front page. -> <del>@tkimnguyen</del> [ in progress #5 @acsr]
- [x] Export the PloneConf2016 Theme from the live theme editor at Plone site "ploneconf_acsrcontent" as zip -> <del>@tkimnguyen</del>   [ in progress #6 @acsr]
- [x] Import into the live site -> <del>@tkimnguyen</del> @acsr
- [x] activate it and do a fast test if it breaks current content ->  [ in progress #6 @acsr] +@tkimnguyen !!

**Please**: Do not publish the content until tested and authorized!
## Create more tickets -> @acsr

The following stuff needs to be propagated into sub-tickets as needed @tkimnguyen @alecpm ??
### The current front page dummy contains blocking stuff:
- [x] remove quotes section [closed #4 @acsr]
- [x] unauthorized quotes with portraits and user (nick)names  [closed #4 @acsr]
- [x] Non working navigation (needs HTML editing in the HTML tiles) [closed, #3]
- [ ] Not properly styled header, footer and sponsor logos
- [ ] The Microsoft NERD center images need authorization: @cewing wanted to take care of this!
- [ ] Insert Microsoft logo in the "A Fantastic Venue to Meet & Work" section of the front page
- [ ] General content approval by the conf com lead team
- [ ] Big Icon / Link area contains placeholder only content.
### Minor issues
- [ ] Sponsor logo padding, margin need to be set.
- [ ] Unused logo placeholders to be removed
- [ ] References of content images to the folder "imagebank" may break due to absolute URL created by TinyMCE.
### Front page publishing needs following related tickets (to be created)
- [x] HTML editing in the rich content tiles of the mosaic layout (maybe just activate the TinyMCE buttons) (implemented; see #3)
- [x] or make the "existing content" tile working in mosaic to use plain editing of subcontent (WONTFIX)
- [ ] TinyMCE Format Menu enhancements with the necessary styles for the front page design (where to add the styles in the less files or TinyMCE config?
### Stuff to be done later in a second step
- [x] Reactivate unused options and links (Commenting out in HTML need plain editing) (fixed by #3)
- [x] Have a responsive Mosaic Slider Tile for image galleries in the design (provided by Nathan, merged by Alec)
- [x] Have the quote dexterity content type from the ploneconf_acsrcontent Plone working prior and during the conference to impress in the media about Plone. [postponed closed #4 @acsr]

**Comment by tkimnguyen** [comment]
We are done, unless @acsr wants to keep working on this :)
